apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: MICRONAUT_SERVER_PORT
              value: "{{ .Values.config.MICRONAUT_SERVER_PORT }}"
            - name: DATASOURCES_DEFAULT_HOST
              value: "{{ .Values.config.DATASOURCES_DEFAULT_HOST }}"
            - name: DATASOURCES_DEFAULT_PORT
              value: "{{ .Values.config.DATASOURCES_DEFAULT_PORT }}"
            - name: DATASOURCES_DEFAULT_DATABASE
              value: "{{ .Values.config.DATASOURCES_DEFAULT_DATABASE }}"
            - name: DATASOURCES_DEFAULT_USERNAME
              value: "{{ .Values.config.DATASOURCES_DEFAULT_USERNAME }}"
            - name: DATASOURCES_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tsdb-credentials
                  key: PATRONI_admin_PASSWORD
            - name: BASEPATH
              value: "{{ .Values.config.BASEPATH }}"