apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "edc.fullname" . }}-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "edc.fullname" . }}-ui
  template:
    metadata:
      labels:
        app: {{ include "edc.fullname" . }}-ui
    spec:
      containers:
      - name: ui
        image: {{ .Values.ui.image }}
        env:
        - name: NEXT_PUBLIC_MANAGEMENT_API_URL
          value: '/api/management'
        - name: NEXT_PUBLIC_MANAGEMENT_API_KEY
          value: {{ .Values.apiKey }}
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edc.fullname" . }}-ui
spec:
  ports:
  - port: 8080
  selector:
    app: {{ include "edc.fullname" . }}-ui