apiVersion: v1
kind: Service
metadata:
  name: {{ include "mqtt-explorer.fullname" . }}
  labels:
    {{- include "mqtt-explorer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ if .Values.oauth2Proxy.enabled }}proxy{{ else }}http{{ end }}
      protocol: TCP
      name: http
  selector:
    {{- include "mqtt-explorer.selectorLabels" . | nindent 4 }}