replicaCount: 1
image:
  repository: fiware/mintaka
  tag: "0.7.0"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
  className: "traefik"
  annotations: {}
  hosts:
    - host: mintaka.local
      paths:
        - path: /ngsi-ld/v1/temporal/entities
          pathType: Prefix
  tls: []

config:
  MICRONAUT_SERVER_PORT: 8080
  DATASOURCES_DEFAULT_HOST: tsdb
  DATASOURCES_DEFAULT_PORT: 5432
  DATASOURCES_DEFAULT_DATABASE: postgres
  DATASOURCES_DEFAULT_USERNAME: admin
  BASEPATH: "/ngsi-ld/v1"