replicaCount: 1

image:
  repository: ghcr.io/thomasnordquist/mqtt-explorer
  pullPolicy: IfNotPresent
  tag: "latest"

oauth2Proxy:
  enabled: false
  image:
    repository: quay.io/oauth2-proxy/oauth2-proxy
    tag: v7.6.0
  clientId: ""
  clientSecret: ""
  cookieSecret: ""
  oidcIssuerUrl: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: "traefik"
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls:[]