replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "alpine"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: "traefik"
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

config:
  orionHost: "orion-ld"
  orionPort: 1026
  mintakaHost: "mintaka"
  mintakaPort: 8080